### ISSUE TITLE
[BUG] -  'AWS_SECRET_ACCESS_KEY' requested on a digital ocean installation 

### ISSUE THREAD

**Issue by alibama** [nebari-dev/nebari#1525]
### OS system and architecture in which you are running QHub

ubuntu 20.04

### Expected behavior

running 

nebari init --guided-init and installing on DO

running on DO  so i've provided the following variables=
SPACES_ACCESS_KEY_ID= ...
SPACES_SECRET_ACCESS_KEY= ...
DIGITALOCEAN_TOKEN= ...

### Actual behavior

here's the output 

anaconda3/lib/python3.9/site-packages/nebari/utils.py:163 in check_cloud_credentials

so you can see that it knows it's supposed to be pulling AWS info, but the variable must be getting requested somewhere?

` │            │   │   'jupyterhub': {                                                           │ │
│ │            │   │   │   'hub_title': 'Nebari - nebari',                                       │ │
│ │            │   │   │   'hub_subtitle': 'Your open source data science platform, hosted on    │ │
│ │            Digital Ocean',                                                                   │ │
│ │            │   │   │   'welcome': 'Welcome! Learn about Nebari\'s features and               │ │
│ │            configurations in <a href="https://ww'+191,                                       │ │
│ │            │   │   │   'logo':                                                               │ │
│ │            'https://raw.githubusercontent.com/nebari-dev/nebari-design/main/logo-mark/horiz… │ │
│ │            │   │   │   'display_version': True                                               │ │
│ │            │   │   }                                                                         │ │
│ │            │   },                                                                            │ │
│ │            │   'helm_extensions': [],                                                        │ │
│ │            │   'monitoring': {'enabled': True},                                              │ │
│ │            │   ... +10                                                                       │ │
│ │            }                                                                                 │ │
│ │ variable = 'AWS_SECRET_ACCESS_KEY'`

### How to Reproduce the problem?

run this on DO with guided init on an ubuntu 20.xx box

**Comment by alibama** [comment]
so i added 
 AWS_ACCESS_KEY_ID and 
AWS_SECRET_ACCESS_KEY
and gave them the same values as the DO variables to see whether that would fix the issue, but it's giving me the error below 

 AWS_ACCESS_KEY_ID and SPACES_ACCESS_KEY_ID must be equal

even though that's now the case (and even though i'm still on DO and assume that AWS defaults mean maybe i should start out testing this on AWS?  glad to do it if that's the case?

thanks again

**Comment by alibama** [comment]
yes - tried a couple of different approaches to nebari init - pip is working fine thanks to some earlier support provided here :)

**Comment by iameskild** [comment]
Thanks for the feedback @alibama! This issue should get fixed in the next release :)

**Comment by alibama** [comment]
hmmm - i made the edits to the init.py and main.py files but still getting the same error - should that work or am i missing something?

**Comment by viniciusdc** [comment]
This is not a bug, this is an expected behavior of the DO terraform provider (unfortunately). Because we use a supported S3 bucket as the backend to the DigitalOcean deployment, the [terraform resource](https://developer.hashicorp.com/terraform/language/settings/backends/s3) requires us to pass the above variables. We had a PR to fix this #1344, due to some circumstances that time we couldn't include that on the release (there was a revert PR).

**Comment by iameskild** [comment]
Closed by #1529
